base/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path('blog/', include('blogapp.urls')),
    path('req/', include('requestapp.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap"
    ),
    path('api/schema/',SpectacularAPIView.as_view(), name="schema"),
    path('api/schema/swagger/',SpectacularSwaggerView.as_view(url_name='schema'), name="swagger"),
    path('api/schema/redoc/',SpectacularRedocView.as_view(url_name='schema'), name="redoc"),
    path('api/', include('myapiapp.urls')),
]

urlpatterns += i18n_patterns(
    path('myauth/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

shopapp/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page
from rest_framework.routers import DefaultRouter
from . import views

app_name = "shopapp"

routers = DefaultRouter()
routers.register("product", views.ProductViewSet)

urlpatterns = [
       # path('', cache_page(20 * 1)(views.ShopIndexView.as_view()), name="index"),          # кеширование отдельного представления на определенное время
       path('', views.ShopIndexView.as_view(), name="index"),
       path('api/', include(routers.urls)),
       path('groups/', views.GroupListView.as_view(), name="group_list"),
       path('products/', views.ProductListView.as_view(), name="products_list"),
       path('products/latest/feed/', views.LatestProductsFeed(), name="products-feed"),
       path('products/export', views.ProductsDataExportView.as_view(), name="products-export"),
       path('products/create', views.ProductCreateView.as_view(), name="product_create"),
       # path('products/create', views.create_product, name="product_create"),
       path('products/<int:pk>', views.ProductDetailView.as_view(), name="product_details"),
       path('products/<int:pk>/update', views.ProductUpdateView.as_view(), name="product_update"),
       path('products/<int:pk>/confirm-delete', views.ProductDeleteView.as_view(), name="product_delete"),
       path('orders/', views.OrdersListView.as_view(), name="orders_list"),
       path('orders/<int:pk>', views.OrdersDetailView.as_view(), name="order_details"),
       path('orders/create', views.create_order, name="order_create"),
]

# urlpatterns = [
#        path('', views.shop_index, name="index"),
#        path('groups/', views.group_list, name="group_list"),
#        path('products/', views.products_list, name="products_list"),
#        path('products/create', views.create_product, name="product_create"),
#        path('orders/', views.orders_list, name="orders_list"),
#        path('orders/create', views.create_order, name="order_create"),
# ]

shopapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.

def product_preview_directory_path(instance: "Product", filename: str):
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )

class Product(models.Model):
    """
    Модель Product представляет товар,
    который можно продавать в интернет-магазине.

    Заказы тут: :model:`shopapp.Order`
    """
    class Meta:
        ordering = ["name", "price"]
        # verbose_name = _("Product")      # перевод в административной модели
        # db_table ="tech_products"
        # verbose_name_plural = "products"

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    @property
    def description_short(self):
        if len(self.description) < 48:
           return self.description
        return self.description[:48] + "..."

    def __str__(self):
        return f"Product(pk={self.pk}, name={self.name!r})"

    def get_absolute_url(self):
        return reverse("shopapp:product_details", kwargs={"pk": self.pk})

def product_images_directory_path(instance: "ProductImage", filename: str):
    return "products/product_{pk}/images/{filename}".format(
        pk=instance.product.pk,
        filename=filename,
    )

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=False,blank=True)


class Order(models.Model):
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    product = models.ManyToManyField(Product, related_name="orders")
    receipt = models.FileField(null=True, upload_to='orders/receipts')

shopapp/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import Group
from .models import Product, Order

class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = 'name',

# 1 variant
# class ProductForm(forms.Form):
#     name = forms.CharField(max_length=100)
#     price = forms.DecimalField(min_value=1, max_value=1000000, decimal_places=2)
#     description = forms.CharField(
#         label="Product description",
#         widget=forms.Textarea(attrs={"rows": 5, "cols": 30}),
#         validators=[validators.RegexValidator(
#            regex=r"great",
#            message="Field must contain word 'great'",
#         )],
#     )

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = 'name', 'price', 'description', 'discount', 'preview'

    images = forms.ImageField(                             # не работает так в 5.0
        widget=forms.ClearableFileInput(attrs={'allow_multiple_selected': True}),
    )



class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = 'delivery_address', 'promocode', 'user', 'product'


class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

shopapp/views.py
"""
В этом модуле лежат различные наборы представлений.

Разные view интернет-магазина: по товарам, заказам и т.д.
"""
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.syndication.views import Feed
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.models import Group
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from timeit import default_timer

from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from .forms import ProductForm, OrderForm, GroupForm
from .models import Product, Order, ProductImage

from rest_framework.viewsets import ModelViewSet
from rest_framework.decorators import action
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.parsers import MultiPartParser
from .serializers import ProductSerializer
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend

from drf_spectacular.utils import extend_schema, OpenApiResponse

import logging

from csv import DictWriter
from .common import save_csv_products

from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.core.cache import cache

log = logging.getLogger(__name__)

@extend_schema(description="Product views CRUD")
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product
    Полный CRUD для сущности товара
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter
    ]
    search_fields = ["name", "description"]
    filterset_fields = [
        "name",
        "description",
        "price",
        "discount",
        "archived",
    ]
    ordering_fields = [
        "name",
        "price",
        "discount"
    ]

    @method_decorator(cache_page(20 * 1))                    # кеширование REST FRAMEWORK через декоратор
    def list(self, *args, **kwargs):
        print("кеширование REST FRAMEWORK")
        return super().list(*args, **kwargs)

    @extend_schema(
        summary="Get one productby ID",
        description="Retrieves **product**, return 404 if not found",
        responses={
            200: ProductSerializer,
            404: OpenApiResponse(description="Empty responce, product by id not found"),
        }
    )
    def retrieve(self, request, *args, **kwargs):
        return super().retrieve(*args, **kwargs)

    @action(methods=['get'], detail=False)                  # выгрузка CSV-файла из БД в rest_framework
    def download_csv(self, request: Request):

        response = HttpResponse(content_type="text/csv")
        filename = "product-export.csv"
        response["Content_Disposition"] = f"attachment; filename={filename}"
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            "name",
            "description",
            "price",
            "discount",
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for product in queryset:
            writer.writerow({
                field: getattr(product, field)
                for field in fields
            })
        return response

    @action(methods=['post'], detail=False, parser_classes=[MultiPartParser],)
    def upload_csv(self, request: Request):
        products = save_csv_products(
            request.FILES["file"].file,
            encoding=request.encoding,
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)


# Create your views here.
class ShopIndexView(View):

    # @method_decorator(cache_page(20 * 1))
    def get(self,request: HttpRequest):
      products = [
        ('Laptop', 1999),
        ('Desktop', 2999),
        ('Smartphone', 999),
      ]
      context = {
        'time_running': default_timer(),
        'products': products,
        'items': 2,
      }
      log.debug("Products for shop index: %s", products)
      log.info("Rendering shop index")
      print("shop index context", context)
      return render(request, 'shopapp/shop-index.html', context=context)

# def shop_index(request: HttpRequest):
#     products = [
#         ('Laptop', 1999),
#         ('Desktop', 2999),
#         ('Smartphone', 999),
#     ]
#     context = {
#         'time_running': default_timer(),
#         'products': products
#     }
#     return render(request, 'shopapp/shop-index.html', context=context)

class GroupListView(View):
    def get(self, request: HttpRequest):
        context = {
            'form': GroupForm(),
            'groups': Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'shopapp/group-list.html', context=context)
    def post(self, request: HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
           form.save()
        return redirect(request.path)

# def group_list(request: HttpRequest):            # 1 variant
#     context = {
#         'groups': Group.objects.prefetch_related('permissions').all(),
#     }
#     return render(request, 'shopapp/group-list.html', context=context)



# class ProductDetailView(View):                     # 2 variant
#     def get(self, request: HttpRequest, pk: int):
#         # product = Product.objects.get(pk=pk)
#         product = get_object_or_404(Product, pk=pk)
#         context = {
#             'product': product
#         }
#         return render(request, 'shopapp/products-details.html', context=context)

class ProductDetailView(DetailView):                     # 3 variant
    template_name = 'shopapp/products-details.html'
    # model = Product
    queryset = Product.objects.prefetch_related("images")
    # print(queryset.values())
    context_object_name = 'product'



class ProductListView(ListView):            # 3 variant
    template_name = 'shopapp/products-list.html'
    # model = Product
    queryset = Product.objects.filter(archived=False)
    context_object_name = 'products'

# class ProductListView(TemplateView):      # 2 variant
#     template_name = 'shopapp/products-list.html'
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['product'] = Product.objects.all()
#         return context

# def products_list(request: HttpRequest):  # 1 variant
#     context = {
#        'products': Product.objects.all(),
#     }
#     return render(request, 'shopapp/products-list.html', context=context)

class ProductCreateView(UserPassesTestMixin, CreateView):                # 1 variant
    def test_func(self):
        # return self.request.user.groups.filter(name="secret-group").exists()
        return self.request.user.is_superuser

    model = Product
    fields = 'name', 'price', 'description', 'discount', 'preview'
    # form_class = ProductForm
    success_url = reverse_lazy("shopapp:products_list")

class ProductUpdateView(UpdateView):
    model = Product
    # fields = 'name', 'price', 'description', 'discount', 'preview'
    form_class = ProductForm                 # групповая загрузка картинок  не работает так в 5.0
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            'shopapp:product_details',
            kwargs={"pk": self.object.pk},
        )

    def form_valid(self, form):
        responce = super().form_valid(form)
        for image in form.files.getlist("images"):
            ProductImage.objects.create(
                product=self.object,
                image=image
            )
        return responce



class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)

class ProductsDataExportView(View):
    def get(self, request: HttpRequest):
        cache_key = "products_data_export"
        products_data = cache.get(cache_key)
        if products_data is None:
            products = Product.objects.order_by("pk").all()
            products_data = [
                {'pk': product.pk,
                 'name': product.name,
                 'price': product.price,
                 'archived': product.archived,
                }
                for product in products
            ]
            cache.set(cache_key, products_data, 300)
        elem = products_data[0]
        name = elem["name"]
        print("name:", name)
        return JsonResponse({"products": products_data})

# def create_product(request: HttpRequest):         # 2 variant
#     if request.method == "POST":
#         form = ProductForm(request.POST)
#         if form.is_valid():
#            #1 name = form.cleaned_data["name"]
#            #2 Product.objects.create(**form.cleaned_data)
#            form.save()
#            url = reverse("shopapp:products_list")
#            return redirect(url)
#     else:
#         form = ProductForm()
#     context = {
#         'form': form,
#     }
#     return render(request, 'shopapp/create-product.html', context=context)

# def orders_list(request: HttpRequest):        # 1 variant
#     context = {
#        'orders':Order.objects.select_related("user").prefetch_related('product').all(),
#     }
#     return render(request, 'shopapp/orders-list.html', context=context)

class OrdersListView(LoginRequiredMixin, ListView):
    queryset = (Order.objects.select_related("user").prefetch_related('product'))

templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
           Base Title
        {% endblock %}

    </title>
</head>
<body>

{% block body %}
   Base body
{% endblock %}

<div>
    {% now 'H:i' %}
</div>
<div>
    {% now 'l' as current_weekday %}
    {{current_weekday}}
</div>


</body>
</html>

templates/shopapp/create-order.html
{% extends 'shopapp/base.html' %}

 {% block title %}
    Create order
 {% endblock %}

{% block body %}
   <h1>Create a new order</h1>
   <div>
       <form method="post">
           {% csrf_token %}

           {{ form.as_p }}

           <button type="submit">
              Create
           </button>
       </form>
   </div>
   <div>
       <a href="{% url 'shopapp:orders_list' %}">Back to orders list</a>
   </div>
{% endblock %}

templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

 {% block title %}
    Create product
 {% endblock %}

{% block body %}
   <h1>Create a new product</h1>
   <div>
       <form method="post">
           {% csrf_token %}

           {{ form.as_p }}

           <button type="submit">
              Create
           </button>
       </form>
   </div>
   <div>
       <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
   </div>
{% endblock %}

templates/shopapp/group-list.html
{% extends 'shopapp/base.html' %}

 {% block title %}
    Group List
 {% endblock %}


{% block body %}
   <h1>Groups</h1>
   <div>
       <form method="post">
           {% csrf_token %}
           {{ form.as_p }}
           <button type="submit">Create</button>
       </form>
   </div>
   <div>
      {% if not groups %}
         <h3>No group yet</h3>
      {% else %}
         <ul>
           {% for group in groups %}
            <li>
               <div>{{ group.name }}</div>
               <ul>
                   {% for permission in group.permissions.all %}
                      <li>
                          {{ permission.name }}
                          (<code>{{ permission.codename }}</code>)
                      </li>
                   {% endfor %}
               </ul>
            </li>
           {% endfor %}
         </ul>
      {% endif %}
    </div>
{% endblock %}

templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

 {% block title %}
    Order #{{ object.pk }} details
 {% endblock %}

{% block body %}
   <h1>Order #<strong>{{ object.pk }}</strong> </h1>
    <div>
             <p>Order by: {% firstof object.user.firstname object.user.username %}</p>
             <p>Delivery address: {{ object.delivery_address }}</p>
             <p>Promocode: <code>{{ object.promocode }}</code></p>
             <div>
                Product in order:
                <ul>
                    {% for product in object.product.all %}
                      <li>{{ product.name }} for $ {{ product.price }}</li>
                    {% endfor %}
                </ul>
             </div>
   <div>
       <a href="{% url 'shopapp:orders_list' %}">Back to orders</a>
   </div>
{% endblock %}

templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

 {% block title %}
    Orders List
 {% endblock %}


{% block body %}
   <h1>Orders</h1>
   {% if not object_list %}
      <h3>No orders yet</h3>
   {% else %}
      <div>
      {% for order in  object_list %}
          <div>
             <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">
                Details: {{ order.pk }}</a></p>
             <p>Order by: {% firstof order.user.firstname order.user.username %}</p>
             <p>Delivery address: {{ order.delivery_address }}</p>
             <p>Promocode: <code>{{ order.promocode }}</code></p>
             <div>
                Product in order:
                <ul>
                    {% for product in order.product.all %}
                      <li>{{ product.name }} for $ {{ product.price }}</li>
                    {% endfor %}
                </ul>
             </div>
          </div>
      {% endfor %}
      </div>
   {% endif %}
   <div>
       <a href="{% url 'shopapp:order_create' %}">Create new order</a>
   </div>

{% endblock %}

templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

 {% block title %}
    Confirm archive (delete) {{ object.name }}
 {% endblock %}

{% block body %}
   <h1>Are you sure want to archive (delete) {{ object.name }}</h1>
   <br>
   <div>
       <a href="{% url 'shopapp:product_details' pk=product.pk %}">Back to products #{{ object.pk }}</a>
   </div>
   <br>
   <div>
       <form method="post">
           {% csrf_token %}

           {{ form.as_p }}

           <button type="submit">
              Archive (Delete)
           </button>
       </form>
   </div>
{% endblock %}

templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

 {% block title %}
    Create product
 {% endblock %}

{% block body %}
   <h1>Create a new product</h1>
   <div>
       <form method="post" enctype="multipart/form-data">
           {% csrf_token %}

           {{ form.as_p }}

           <button type="submit">
              Create
           </button>
       </form>
   </div>
   <div>
       <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
   </div>
{% endblock %}

templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

 {% block title %}
    Update product
 {% endblock %}

{% block body %}
   <h1>Update product</h1>
   <div>
       <form method="post" enctype="multipart/form-data">
           {% csrf_token %}

           {{ form.as_p }}

           <button type="submit">
              Update
           </button>
       </form>
   </div>
   <div>
       <a href="{% url 'shopapp:product_details' pk=product.pk %}">Back to products #{{ object.pk }}</a>
   </div>
{% endblock %}

templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}

 {% block title %}
    Product #{{ product.pk }}
 {% endblock %}

{% block body %}
   <h1>Product <strong>{{ product.name }}</strong> </h1>
   <div>
        <div>Description: <em>{{ product.description }}</em></div>
        <div>Price: {{ product.price }}</div>
        <div>Discount: {{ product.discount }}</div>
        <div>Archived: {{ product.archived }}</div>
        {% if product.preview %}
            <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
        {% endif %}
       <h3>Images:</h3>
       <div>
           {% for img in product.images.all %}
             <div>
                <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
                 <div>{{ img.description }}</div>
             </div>
           {% empty %}
             <div>No images uploads yet</div>
           {% endfor %}
       </div>
   </div>
   <div>
       <a href="{% url 'shopapp:product_update' pk=product.pk %}">Update product</a>
   </div>
   <div>
       <a href="{% url 'shopapp:product_delete' pk=product.pk %}">Archive (Delete) product</a>
   </div>
   <div>
       <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
   </div>
{% endblock %}

templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

 {% block title %}
   {% translate 'Products List' %}
 {% endblock %}


{% block body %}
   <h1>{% translate 'Products' %}</h1>
   {% if not products %}
      {% url 'shopapp:product_create' as create_product_url %}
      {% blocktranslate %}
      <h3>No products yet</h3>
      <a href="{{ create_product_url }}"
       >Create a new product</a>
      {% endblocktranslate %}
   {% else %}
      <div>
      {% blocktranslate count products_count=products|length %}
       There is only one product.
      {% plural %}
       There are {{ products_count }} products.
      {% endblocktranslate %}
      </div>
      <div>
      {% for product in  products %}
          <div>
             <p><a href="{% url 'shopapp:product_details' pk=product.pk %}">
                {% translate 'Name' context 'product name' %}: {{ product.name }}</a></p>
             <p>{% translate 'Price' %}: {{ product.price }}</p>
              {% translate 'no discount' as no_discount %}
             <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>

             {% if product.preview %}
               <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
             {% endif %}

          </div>
      {% endfor %}
      </div>
   <div>
       <a href="{% url 'shopapp:product_create' %}"
       >{% translate 'Create new product' %}</a>
   </div>

   {% endif %}
{% endblock %}

templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls %}
 <li>
     <a href="{% url 'admin:import_products_csv' %}" class="addlink">
         Import CSV
     </a>
 </li>
 {{ block.super }}
{% endblock %}

templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}
{% load cache %}

 {% block title %}
    Shop Index
 {% endblock %}


{% block body %}
 <h1>Hello Shop</h1>

<div>
    <ul>
        {% for name, price in products %}
          <li>{{ name }} ({{ name|length}}) for $ {{ price }}</li>
          {% if name|length_is:'7' %}
             <span>Lucky product</span>
          {% endif %}

        {% empty %}
           No products here
        {% endfor %}
    </ul>
</div>
 <div>
    <strong>
       You have {{ items }} cherr{{ items|pluralize:"y,ies" }}   <!-- Окончания для единственного и множественного числа-->
    </strong>
 </div>

 <div>
    Time running: {{ time_running }}
 </div>

 {% cache 10 lorem %}
 <div>
     {% lorem 3 p random %}
 </div>
 {% endcache %}


{% endblock %}