base/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path('blog/', include('blogapp.urls')),
    path('req/', include('requestapp.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap"
    ),
    path('api/schema/',SpectacularAPIView.as_view(), name="schema"),
    path('api/schema/swagger/',SpectacularSwaggerView.as_view(url_name='schema'), name="swagger"),
    path('api/schema/redoc/',SpectacularRedocView.as_view(url_name='schema'), name="redoc"),
    path('api/', include('myapiapp.urls')),
]

urlpatterns += i18n_patterns(
    path('myauth/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from . import views

app_name = "myauth"

urlpatterns = [
       # path('login/', views.login_view, name="login"),
       path('login/',
            LoginView.as_view(template_name="myauth/login.html", redirect_authenticated_user=True,),
            name="login"),
       path('logout/', views.logout_view, name="logout"),
       path('users/', views.UserListView.as_view(), name="users_list"),
       path('users/<int:pk>/about-me', views.AboutMeView.as_view(), name="about-me"),
       path('users/<int:pk>/about-me/update',
            views.UserUpdateView.as_view(template_name="myauth/user_update_form.html"),
            name="user_update"),
       path('register/', views.RegisterView.as_view(), name="register"),
       # path('logout/', views.MyLogoutView.as_view(), name="logout"), # не работает в 5.0
       path("cookie/get/", views.get_cookie_view, name="cookie-get"),
       path("cookie/set/", views.set_cookie_view, name="cookie-set"),
       path("session/set/", views.set_session_view, name="session-get"),
       path("session/get/", views.get_session_view, name="session-set"),
       path("foo-bar/", views.FooBarView.as_view(), name="foo-bar"),
       path("hello/", views.HelloView.as_view(), name="hello"),

]

myauth/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


def avatar_images_directory_path(instance: "Profile", filename: str):
    return "avatar/user_{pk}/images/{filename}".format(
        pk=instance.user.pk,
        filename=filename,
    )
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    image = models.ImageField(null=True, blank=True, upload_to=avatar_images_directory_path)

myauth/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    # pass
    class Meta:
        model = User
        fields = 'username', 'first_name', 'last_name', 'email'


    bio = forms.CharField(initial="")
    images = forms.ImageField()

myauth/views.py
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LogoutView
from django.core.exceptions import ObjectDoesNotExist
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView

from django.views.decorators.cache import cache_page

from .models import Profile
from .forms import UserForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _, ngettext

from random import random
# Create your views here.

class HelloView(View): # локализация данных
    welcome_message = _("welcome hello world")

    def get(self, request: HttpRequest):
        items_str = request.GET.get('items') or 0
        items = int(items_str)
        products_line = ngettext(
            "one product",
            "{count} products",
            items,
        )
        products_line = products_line.format(count=items)
        return HttpResponse(
            f"<h1>{self.welcome_message}</h1>"
            f"\n<h2>{products_line}</h2>"
        )




def login_view(request: HttpRequest):
    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect('/admin/')

        return render(request, 'myauth/login.html')
    username = request.POST["username"]
    password = request.POST["password"]

    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('/admin/')
    return render(request, "myauth/login.html", {"error": "Invalid login credentials"})

# class AboutMeView(TemplateView):
#     template_name = 'myauth/about-me.html'

class AboutMeView(DetailView):
    template_name = 'myauth/about-me.html'
    queryset = User.objects.all()
    context_object_name = 'user'

class UserListView(ListView):
    template_name = 'myauth/users-list.html'
    # model = Product
    queryset = User.objects.all()
    context_object_name = 'users'

class UserUpdateView(UpdateView):
    model = User
    # fields = 'name', 'price', 'description', 'discount', 'preview'
    form_class = UserForm
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            'myauth:about-me',
            kwargs={"pk": self.object.pk},
        )

    def form_valid(self, form):
            responce = super().form_valid(form)
            bio = form.cleaned_data["bio"]
            image = form.files.get("images")
            try:
                tom = Profile.objects.get(user_id=self.object.pk)
                tom.user = self.object
                tom.bio = bio
                tom.image = image
                tom.save()
            except ObjectDoesNotExist:
                Profile.objects.create(
                    user=self.object,
                    bio=bio,
                    image=image
                )
            return responce


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'myauth/register.html'
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        responce = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return responce
def logout_view(request: HttpRequest):
    logout(request)
    return redirect(reverse("myauth:login"))

# class MyLogoutView(LogoutView):
#     next_page = reverse_lazy("myauth:login")

@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest):
    responce = HttpResponse("Cookie set")
    responce.set_cookie("fizz", "buzz", max_age=3600)
    return responce

@cache_page(20 * 1)                                        # кэширование на 20 секунд
def get_cookie_view(request: HttpRequest):
    value =request.COOKIES.get("fizz", "default value")
    return HttpResponse(f"Cookie value: {value!r} + {random()}")

@permission_required("myauth.view_profile", raise_exception=True)
def set_session_view(request: HttpRequest):
    request.session["foobar"] = "spameggs"
    return HttpResponse("Session set!")

@login_required
def get_session_view(request: HttpRequest):
    value = request.session.get("foobar", "default")
    return HttpResponse(f"Session value: {value!r}")



class FooBarView(View):
    def get(self, request: HttpRequest):
        return JsonResponse({'foo': 'bar', 'spam': 'eggs'})

templates/myauth/about-me.html
{% extends 'myauth/base.html' %}
{% load cache %}

 {% block title %}
    User # {{ user.pk}}
 {% endblock %}


{% block body %}
   <h1>User # {{ user.pk}} info</h1>
        {% cache 300 userinfo user.username %}
          <h2>Detail</h2>
          <p>Username: {{ user.username }}</p>
          <p>First name: {{ user.first_name }}</p>
          <p>Last name: {{ user.last_name }}</p>
          <p>Email: {{ user.email }}</p>
          <p>Bio: {{ user.profile.bio }}</p>
        {% endcache %}
        <h3>Avatar:</h3>
        <div>
           {% if user.profile.image %}
           <img src="{{ user.profile.image.url }}" alt="{{ user.profile.image.name }}">
           {% else %}
             <p>Avatar is not load</p>
           {% endif %}
        </div>
        <div>
            <a href="{% url 'myauth:user_update' pk=user.pk %}">Update user data</a>
        </div>
        <div>
            <a href="{% url 'myauth:users_list' %}">Back to users list</a>
        </div>
{% endblock %}

<!--   {% if user.is_authenticated %}-->
<!--   {% else %}-->
<!--      <h2>User is anonymous</h2>-->
<!--   {% endif %}-->

<!--         <div>-->
<!--           <form method="post" enctype="multipart/form-data">-->
<!--            {% csrf_token %}-->
<!--            <p>-->
<!--              <label for="id_avatar">Avatar</label>-->
<!--              <input name="avatar" required id="id_avatar" type="file">-->
<!--            </p>-->

<!--            <button type="submit">Create (update) avatar</button>-->
<!--           </form>-->
<!--         </div>-->

templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
           Base Title
        {% endblock %}

    </title>
</head>
<body>

{% block body %}
   Base body
{% endblock %}

</body>
</html>

templates/myauth/login.html
{% extends 'myauth/base.html' %}

 {% block title %}
    Login
 {% endblock %}


{% block body %}
   <h1>Login</h1>

   <div>
       <form method="post">
           {% csrf_token %}

           {{ form.as_p }}
<!--           {% if error %}-->
<!--            <p style="color: red">-->
<!--               {{ error }}-->
<!--            </p>-->
<!--           {% endif %}-->
<!--          <p>-->
<!--           <label for="username">Username:</label>-->
<!--           <input type="text" id="username" name="username" required>-->
<!--          </p>-->
<!--          <p>-->
<!--           <label for="password">Password:</label>-->
<!--           <input type="password" id="password" name="password" required>-->
<!--          </p>-->

           <button type="submit">
              Login
           </button>
       </form>
   </div>
{% endblock %}

templates/myauth/register.html
{% extends 'myauth/base.html' %}

 {% block title %}
    Register
 {% endblock %}

{% block body %}
   <h1>Register</h1>
       <form method="post">
           {% csrf_token %}
           {{ form.as_p }}
           <input type="submit" value="Register">
       </form>
{% endblock %}

templates/myauth/user_update_form.html
{% extends 'myauth/base.html' %}

 {% block title %}
    Update user info
 {% endblock %}

{% block body %}
   <h1>Update user info</h1>
   <div>
       <form method="post" enctype="multipart/form-data">
           {% csrf_token %}

           {{ form.as_p }}

           <button type="submit">
              Update
           </button>
       </form>
   </div>
   <div>
       <a href="{% url 'myauth:about-me' pk=user.pk %}">Back to users #{{ object.pk }}</a>
   </div>
{% endblock %}

templates/myauth/users-list.html
{% extends 'myauth/base.html' %}

 {% block title %}
    Users List
 {% endblock %}


{% block body %}
   <h1>Users</h1>
   {% if not users %}
      <h3>No users yet</h3>
   {% else %}
      <div>
      {% for user in  users %}
          <div>

             <p><a href="{% url 'myauth:about-me' pk=user.pk %}">
               Username: #{{ user.pk }} {{ user.username }}  </a></p>
             <p>First name: {{ user.first_name }}</p>
             <p>Last name: {{ user.last_name }}</p>
             <p>Email: {{ user.email }}</p>
             <p>Bio: {{ user.profile.bio }}</p>
             <p>Avatar</p>
             <div>
               {% if user.profile.image %}
                  <img src="{{ user.profile.image.url }}" alt="{{ user.profile.image.name }}">
               {% endif %}
             </div>
          </div>


      {% endfor %}
      </div>
   {% endif %}

   <div>
       <a href="{% url 'myauth:register' %}">Register a new user</a>
   </div>
{% endblock %}